#pragma config(Sensor, dgtl1,  driveModePin,   sensorDigitalIn)
#pragma config(Sensor, dgtl3,  aut0,           sensorDigitalIn)
#pragma config(Sensor, dgtl4,  aut1,           sensorDigitalIn)
#pragma config(Sensor, dgtl5,  aut2,           sensorDigitalIn)
#pragma config(Motor,  port1,           L1,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           L2,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           L3,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           L4,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           arm,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           intake,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           R4,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           R3,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           R2,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          R1,            tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define TILE 800.0	//FIXME
#define TURN 600.0	//FIXME

task autonSelection();
task blinkRedLEDHalfSec();
task blinkGreenLEDHalfSec();

void fineControl();

int auton = 0;

//Tank is 0, arcade is 1
short driveMode;

#include "Vex_Competition_Includes.c"

void LDrive(int pwr)
{
	motor[L1] = motor[L2] = motor[L3] = motor[L4] = pwr;
}
void RDrive(int pwr)
{
	motor[R1] = motor[R2] = motor[R3] = motor[R4] = pwr;
}

void arcade(int mov, int rot)
{
	LDrive(mov + rot);
	RDrive(mov - rot);
}

void tank(int ld, int rd)
{
	LDrive(ld);
	RDrive(-    rd);
}

void goRobit(int lpwr, int rpwr, int time)
{
	LDrive(lpwr);
	RDrive(-rpwr);
	wait1Msec(time);
	LDrive(0);
	RDrive(0);
}

void goRobit(int lpwr, int rpwr)
{
	LDrive(lpwr);
	RDrive(rpwr);
}

void BFAuton()
{
	goRobit(-127, -127, TILE * 2);
	goRobit(127, 127, TILE * 3);
	goRobit(127, -127, TURN);
	goRobit(127, 127, TILE * 2);
}
void BPAuton()
{
	//goRobit(127, 127, TILE * 3);
//	goRobit(-127, -127, TILE * 3);

	goRobit(127, 127, TILE);
	goRobit(127, -127, TURN);
	goRobit(127, 127, TILE * 2);
	goRobit(-127, -127, TILE * 0.75);
	goRobit(127, -127, TURN);
	goRobit(127, 127, TILE * 2.5);
}
void RFAuton()
{
	goRobit(-127, -127, TILE * 2);
	goRobit(127, 127, TILE * 2.85);
	goRobit(-127, 127, TURN);
	goRobit(127, 127, TILE * 2);
}
void RPAuton()
{
	goRobit(127, 127, TILE * 0.6);
	goRobit(-127, 127, TURN);
	motor[intake] = 127;
	goRobit(127, 127, TILE * 1.25); //2 goes past the line
	goRobit(-127, -127, TILE * 0.2);
	motor[intake] = 0;
	goRobit(-127, 127, TURN * 0.75);
	goRobit(127, 127, TILE * 1.5);
}

void simpleAuton()
{
	motor[intake] = 127;
	goRobit(127, 127, TILE * 2.25);
	motor[intake] = 0;

}

void autonRunner()
{
	auton = 0;
	// !SensorValue defines if the pin is in (not out)
	if(!SensorValue(aut0))
	{
		auton += 1;
	}
	if(!SensorValue(aut1))
	{
		auton += 2;
	}
	if(!SensorValue(aut2))
	{
		auton += 4;
	}

	switch(auton)
	{
		case 0:
			simpleAuton();
			break;
		case 1:
			BFAuton();
			break;
		case 2:
			BPAuton();
			break;
		case 3:
			RFAuton();
			break;
		case 4:
			RPAuton();
			break;
		default:
			simpleAuton();
			break;
	}
}

void pre_auton() { }

task autonomous
{
	autonRunner();
}

task usercontrol
{
	while(true)
	{
		if(vexRT[Btn7U])
		{
			autonRunner();
		}

		if(SensorValue(driveModePin))
		{
			driveMode = 0;
		}
		else
		{
			driveMode = 1;
		}

		if(vexRT[Btn8U] || vexRT[Btn8D] || vexRT[Btn8L] || vexRT[Btn8R])
		{
			fineControl();
		}
		else
		{
			if(driveMode)
			{
				arcade(vexRT[Ch1], vexRT[Ch2]);
			}
			else
			{
				tank(vexRT[Ch3], vexRT[Ch2]);
			}
		}
		if(vexRT[Btn5U])
		{
			motor[arm] = 127;
		}
		else if(vexRT[Btn5D])
		{
			motor[arm] = -127;
		}
		else
		{
			motor[arm] = 0;
		}
		if(vexRT[Btn6U])
		{
			motor[intake] = 127;
		}
		else if(vexRT[Btn6D])
		{
			motor[intake] = -127;
		}
		else
		{
			motor[intake] = 0;
		}
	}
}
void fineControl()
{
	if(vexRT[Btn8U])
	{
		LDrive(40);
		RDrive(-40);
	}
	else if(vexRT[Btn8R])
	{
		LDrive(40);
		RDrive(40);
	}
	else if(vexRT[Btn8L])
	{
		LDrive(-40);
		RDrive(-40);
	}
	else if(vexRT[Btn8D])
	{
		LDrive(-40);
		RDrive(40);
	}
	else
	{
		LDrive(0);
		RDrive(0);
	}
}
