#pragma config(Motor,  port1,           L1,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           L2,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           L3,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           L4,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           arm,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           intake,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           R4,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           R3,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           R2,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          R1,            tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define TILE 800.0	//FIXME
#define TURN 700.0	//FIXME


#include "Vex_Competition_Includes.c"

void LDrive(int pwr)
{
	motor[L1] = motor[L2] = motor[L3] = motor[L4] = pwr;
}
void RDrive(int pwr)
{
	motor[R1] = motor[R2] = motor[R3] = motor[R4] = pwr;
}

void arcade(int mov, int rot)
{
	LDrive(mov + rot);
	RDrive(mov - rot);
}
void goRobit(int lpwr, int rpwr, int time)
{
	LDrive(lpwr);
	RDrive(-rpwr);
	wait1Msec(time);
	LDrive(0);
	RDrive(0);
}

void BFAuton()
{
	goRobit(-127, -127, TILE * 2);
	goRobit(127, 127, TILE * 3);
	goRobit(127, -127, TURN);
	goRobit(127, 127, TILE * 2);
}
void BPAuton()
{
	//goRobit(127, 127, TILE * 3);
//	goRobit(-127, -127, TILE * 3);

	goRobit(127, 127, TILE);
	goRobit(127, -127, TURN);
	goRobit(127, 127, TILE * 2);
	goRobit(-127, -127, TILE * 0.75);
	goRobit(127, -127, TURN);
	goRobit(127, 127, TILE * 2.5);
}
void RFAuton()
{
	goRobit(-127, -127, TILE * 2);
	goRobit(127, 127, TILE * 3);
	goRobit(-127, 127, TURN);
	goRobit(127, 127, TILE * 2);
}
void RPAuton()
{
	goRobit(127, 127, TILE);
	goRobit(-127, 127, TURN);
	goRobit(127, 127, TILE * 2);
	goRobit(-127, -127, TILE * 0.75);
	goRobit(-127, 127, TURN);
	goRobit(127, 127, TILE * 2.5);
}

void simpleAuton()
{
	motor[intake] = 127;
	goRobit(127, 127, TILE * 2.25);
	motor[intake] = 0;

}

void pre_auton() { }

task autonomous
{
	simpleAuton();
}

task usercontrol
{
	while(true)
	{
		arcade(vexRT[Ch1], vexRT[Ch2]);
		if(vexRT[Btn5U])
		{
			motor[arm] = 127;
		}
		else if(vexRT[Btn5D])
		{
			motor[arm] = -127;
		}
		else
		{
			motor[arm] = 0;
		}
		if(vexRT[Btn6U])
		{
			motor[intake] = 127;
		}
		else if(vexRT[Btn6D])
		{
			motor[intake] = -127;
		}
		else
		{
			motor[intake] = 0;
		}
	}
}
