#pragma config(Motor,  port1,           BLDrive,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           FLDrive2,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           FLDrive1,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           FRDrive1,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           FRDrive2,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          BRDrive,       tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Vex_Competition_Includes.c"
#include "utils.c"

//Turns on the left drive to the provided power
void LDrive(int pwr)
{
	motor[FLDrive1] = motor[FLDrive2] = motor[BLDrive] = pwr;
}
//Turns on the right drive to the provided power
void RDrive(int pwr)
{
	motor[FRDrive1] = motor[FRDrive2] = motor[BRDrive] = pwr;
}
void goRobit(int pwr, int timems)
{
	RDrive(pwr);
	LDrive(pwr);
	wait1Msec(timems);
	RDrive(pwr);
	LDrive(pwr);
}

void tank(int lpwr, int rpwr)
{
	LDrive(lpwr);
	RDrive(rpwr);
}
void arcade(int mov, int rot)
{
	LDrive(mov + rot);
	RDrive(mov - rot);
}

void pre_auton()
{

}
void topAuton()
{
	goRobit(127, 1250);
}
void bottomAuton()
{
	goRobit(127, 2000);
}
task autonomous
{
	//topAuton();
	//bottomAuton();
}

task usercontrol
{
	while(true)
	{
		//tank(,);
		arcade(vexRT[Ch1], vexRT[Ch2]);
	}
}
