#pragma config(Motor,  port2,           FLDrive1,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           FLDrive2,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           BLDrive,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           FRDrive1,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           FRDrive2,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           BRDrive,       tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Vex_Competition_Includes.c"

void LDrive(int pwr)
{
	motor[FLDrive1] = motor[FLDrive2] = motor[BLDrive] = pwr;
}
void RDrive(int pwr)
{
	motor[FRDrive1] = motor[FRDrive2] = motor[BRDrive] = pwr;
}

void tank(int lpwr, int rpwr)
{
	LDrive(lpwr);
	RDrive(rpwr);
}
void arcade(int mov, int rot)
{
	LDrive(mov + rot);
	RDrive(mov - rot);
}

void pre_auton()
{

}

task autonomous
{

}

task usercontrol
{
	while(true)
	{
		//tank(,);
		//arcade(,);
	}
}
