#pragma config(Motor,  port1,           BLDrive,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           FLDrive2,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           FLDrive1,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           FRDrive1,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           FRDrive2,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          BRDrive,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Vex_Competition_Includes.c"


//SET ME BEFORE A MATCH
#define USEAUTON true



//Turns on the left drive to the provided power
void LDrive(int pwr)
{
	motor[FLDrive1] = motor[FLDrive2] = motor[BLDrive] = pwr;
}
//Turns on the right drive to the provided power
void RDrive(int pwr)
{
	motor[FRDrive1] = motor[FRDrive2] = motor[BRDrive] = pwr;
}
void goRobit(int pwr, int timems)
{
	RDrive(-pwr);
	LDrive(pwr);
	wait1Msec(timems);
	RDrive(0);
	LDrive(0);
}
void goRobit(int lpwr, int rpwr, int time)
{
	RDrive(-rpwr);
	LDrive(lpwr);
	wait1Msec(time);
	RDrive(0);
	LDrive(0);
}

void tank(int lpwr, int rpwr)
{
	LDrive(lpwr);
	RDrive(rpwr);
}
void arcade(int mov, int rot)
{
	LDrive(mov + rot);
	RDrive(mov - rot);
}

void pre_auton()
{

}
void topBlueAuton()
{
	goRobit(-127, 1250);
	goRobit(127, 700);
	goRobit(127, -127, 450);
	goRobit(127, 750);
	goRobit(-127, 500);
}
void bottomBlueAuton() //BROKE, FIXME turns too far
{
	goRobit(-127, 400);
	goRobit(127, -127, 600);
	goRobit(127, 1500);
}
void topRedAuton()
{
	goRobit(-127, 1250);
	goRobit(127, 700);
	goRobit(-127, 127, 450);
	goRobit(127, 750);
	goRobit(-127, 500);
}
void bottomRedAuton() //BROKE, FIXME
{
	goRobit(-127, 400);
	goRobit(-127, 127, 600);
	goRobit(127, 1500);
}
task autonomous
{
	if(USEAUTON)
	{
		topBlueAuton();
	}
}

task usercontrol
{
	while(true)
	{
		/*
		if(vexRT[Btn7D])
		{
			topBlueAuton();
		}
		else if(vexRT[Btn7U])
		{
			topRedAuton();
		}
		*/
		arcade(vexRT[Ch1], vexRT[Ch2]);
	}
}
