#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  bump,           sensorTouch)
#pragma config(Sensor, I2C_1,  FRDriveIME,     sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  FLDriveIME,     sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  FStrafeIME,     sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  BStrafeIME,     sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           strafeBack,    tmotorVex393_HBridge, openLoop, reversed, encoderPort, I2C_4)
#pragma config(Motor,  port2,           driveFR,       tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port3,           driveFL,       tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port4,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           driveBR,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           driveBL,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          strafeFront,   tmotorVex393_HBridge, openLoop, encoderPort, I2C_3)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Vex_Competition_Includes.c"

const float TICKS_PER_DEGREE = 1.0888889;

//MAGIC
int sign(int x)
{
	return (x > 0) - (x < 0);
}

int drive = 0;
//int bumpSwitchState = 0;
//int numberOfDriveModes = 4;

// Drive functions
void LDrive(int pwr)
{
	motor[driveBL] = pwr;
	motor[driveFL] = pwr;
}
void RDrive(int pwr)
{
	motor[driveBR] = pwr;
	motor[driveFR] = pwr;
}
void Strafe(int pwr)
{
	motor[strafeBack] = pwr;
	motor[strafeFront] = pwr;
}
void ResetAllI2CEncoders()
{
	nMotorEncoder[FRDriveIME] = nMotorEncoder[FLDriveIME] = nMotorEncoder[FStrafeIME] = nMotorEncoder[BStrafeIME] = 0;
}

// Auton functions
/*
Neil_6121C 8 Dec 2017 Pennsylvania 6121C said:
If you are using a 393 motor, the number of ticks per revolution [counted by the I2C] will be:

627.2 for torque gearing
392 for high speed gearing
261.333 for turbo gearing
*/
/*
Current configuration:
All drive motors: high speed
Strafe: high speed
*/

//Counted out of 360 degrees
void moveDegrees(int motorDegrees)
{
	//resets the encoders in preperation for population
	ResetAllI2CEncoders();
	int ticksToMove = round(motorDegrees * TICKS_PER_DEGREE);
	//turns motors on, returns if luser wants to rotate 0 degrees
	if(ticksToMove > 0)
	{
		LDrive(127);
		RDrive(127);
	}
	else if(ticksToMove < 0)
	{
		LDrive(-127);
		RDrive(-127);
	}
	else
	{
		return;
	}
	//waits for .25 seconds to populate the IMEs
	wait1Msec(250);
	//Dont bother turning off the motors, we're just going to reset the values later in this function
	//LDrive(0);
	//RDrive(0);
	float difference = nMotorEncoder[FLDriveIME] - nMotorEncoder[FRDriveIME];
	float leftPwr = (127 - (127 * (difference / 100)));
	if(leftPwr > 127)
	{
		leftPwr = 127;
	}
	float rightPwr = (127 + (127 * (difference / 100)));
	if(rightPwr > 127)
	{
		rightPwr = 127;
	}
	LDrive(leftPwr);
	RDrive(rightPwr);
	while(nMotorEncoder[FLDriveIME] <= ticksToMove && nMotorEncoder[FRDriveIME] <= ticksToMove)
	{
		//wait with them on
	}
	LDrive(0);
	RDrive(0);
}
//turn right is positive
//up to user to determine how many degrees of _motor rotation_ it will take to get 360 degrees of _robot rotation_
//user aka me
void rotDegrees(int motorDegrees)
{
	int ticksToMove = motorDegrees * TICKS_PER_DEGREE;
	LDrive(sign(motorDegrees) * 127);
	RDrive(-sign(motorDegrees) * 127);
	while(nMotorEncoder[FLDriveIME] <= ticksToMove && nMotorEncoder[FRDriveIME] <= ticksToMove)
	{

	}
	LDrive(0);
	RDrive(0);
}
//strafe right is positive
void strafeDegrees(int motorDegrees)
{
	int ticksToMove = motorDegrees * TICKS_PER_DEGREE;
	Strafe(sign(motorDegrees) * 127);
	while(nMotorEncoder[FStrafeIME] <= ticksToMove && nMotorEncoder[BStrafeIME] <= ticksToMove)
	{

	}
	Strafe(0);
}

// Drive modes
void tank(int left, int right, int strafe)
{
	LDrive(left);
	RDrive(right);
	motor[strafeBack] = (strafe - (left - right));
	motor[strafeFront] = (strafe + (left - right));
}
void arcade(int mov, int rot, int strafe)
{
	LDrive(mov + rot);
	RDrive(mov - rot);
	motor[strafeBack] = (strafe - rot);
	motor[strafeFront] = (strafe + rot);
}

void auton()
{

}

// VEX Functions/Tasks
void pre_auton()
{

}
task autonomous()
{
	//auton();
}
task usercontrol()
{
	while(true)
	{
		/*
		if(SensorValue[bump] == 1)
		{
			while(SensorValue[bump] == 1)
			{

			}
			drive++;
		}
		if(drive>=4)
		{
			drive=0;
		}
		if(drive == 0)
		{
			arcade(vexRT[Ch3], vexRT[Ch1], vexRT[Ch4]);
		}
		else if(drive == 1)
		{
			arcade(vexRT[Ch2], vexRT[Ch1], vexRT[Ch4]);
		}
		else if(drive == 2)
		{
			arcade(vexRT[Ch2], vexRT[Ch4], vexRT[Ch1]);
		}
		else if(drive == 3)
		{
			tank(vexRT[Ch3], vexRT[Ch2], vexRT[Ch1]);
		}
		*/
		arcade(vexRT[Ch3], vexRT[Ch1], vexRT[Ch4]);

	}
}
