#pragma config(Sensor, I2C_1,		IMencoder,     sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           mainmotor,          tmotorVex393_HBridge, openLoop, reversed, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float targetPoint;

#define MULTIPLIER -2
#define MAX 10
#define THRESHOLD 5 //ticks

void ResetDriveI2CEncoders()
{
	nMotorEncoder[mainmotor] = 0;
}
void InitPID()
{
	targetPoint = 0;
	ResetDriveI2CEncoders();
}
void setTargetPoint(bool go, int direction, int currentPoint)
{
	if(go)
	{
		if(direction>0)
		{
			targetPoint++;
		}
		else if(direction<0)
		{
			targetPoint--;
		}
		if(targetPoint>currentPoint+MAX)
		{
			targetPoint = currentPoint+MAX;
		}
		else if(targetPoint<currentPoint-MAX)
		{
			targetPoint = currentPoint-MAX;
		}
	}
}
int PID(int currentPoint)
{
	int power;
	if(targetPoint > currentPoint-THRESHOLD || targetPoint < currentPoint+THRESHOLD)
	{
		power = MULTIPLIER * (targetPoint - currentPoint);
	}
	if(power > 127)
	{
		power = 127;
	}
	else if(power < -127)
	{
		power = -127;
	}
	return power;
}

task main()
{
	InitPID();
	while(true)
	{
		if(vexRT[Btn6U])
		{
			setTargetPoint(true, 1, nMotorEncoder[mainmotor]);
		}
		else if(vexRT[Btn6D])
		{
			setTargetPoint(true, -1, nMotorEncoder[mainmotor]);
		}
		motor[mainmotor] = PID(nMotorEncoder[mainmotor]);
	}
}
