#pragma config(Motor,  port1,           L1Drive,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           L2Drive,       tmotorVex393_MC29, openLoop, encoderPort, None)
#pragma config(Motor,  port3,           L3Drive,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           L4Drive,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Intake2,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           R4Drive,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           R3Drive,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           R2Drive,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          R1Drive,       tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Vex_Competition_Includes.c"

void LDrive(int prw)
{
	motor[L1Drive] = motor[L2Drive] = motor[L3Drive] = motor[L4Drive]= prw;
}
void RDrive(int prw)//function to turn on the right drive
{
	motor[R1Drive] = motor[R2Drive] = motor[R3Drive] = motor[R4Drive] = prw;
}

//Driver Control funcs
void arcade(int move, int rot)
{
	LDrive(move + rot);
	RDrive(move - rot);
}
void pre_auton(){}
task autonomous()
{

}
task usercontrol()
{
	while(true)
	{
		arcade(vexRT[Ch1], vexRT[Ch2]);
		motor[Intake2] = vexRT[Ch3];
	}
}
