#pragma config(Motor,  port1,           L1Drive,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           L2Drive,       tmotorVex393_MC29, openLoop, encoderPort, None)
#pragma config(Motor,  port3,           L3Drive,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           L4Drive,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Intake2,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           R4Drive,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           R3Drive,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           R2Drive,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          R1Drive,       tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define ONE_TILE 1250 //FIXME
#define ONE_ROT 750 //FIXME

void flagToPlatformSRT(int isBlue);

#include "Vex_Competition_Includes.c"

void LDrive(int prw)
{
	motor[L1Drive] = motor[L2Drive] = motor[L3Drive] = motor[L4Drive]= prw;
}
void RDrive(int prw)//function to turn on the right drive
{
	motor[R1Drive] = motor[R2Drive] = motor[R3Drive] = motor[R4Drive] = prw;
}

void goRobit(int lpwr, int rpwr, int time)
{
	LDrive(lpwr);
	RDrive(rpwr);
	wait1Msec(time);
	LDrive(0);
	RDrive(0);
}

//Driver Control funcs
void arcade(int move, int rot)
{
	LDrive(move + rot);
	RDrive(move - rot);
}

void bnfa()
{
	goRobit(-127, -127, ONE_TILE * 2);
	flagToPlatformSRT(1);
}
void bffa()
{
	goRobit(127, 127, ONE_TILE);
	goRobit(127, -127, ONE_ROT);
	goRobit(127, 127, ONE_TILE * 2);
	goRobit(-127, -127, ONE_TILE);
	goRobit(127, -127, ONE_ROT);
	goRobit(127, 127, ONE_TILE * 1.5);
}
void rnfa()
{
	goRobit(-127, -127, ONE_TILE * 2);
	flagToPlatformSRT(-1);
}
void rffa()
{
	goRobit(127, 127, ONE_TILE);
	goRobit(-127, 127, ONE_ROT);
	goRobit(127, 127, ONE_TILE * 2);
	goRobit(-127, -127, ONE_TILE);
	goRobit(-127, 127, ONE_ROT);
	goRobit(127, 127, ONE_TILE * 1.5);
}

void pre_auton(){}

task autonomous()
{

}

task usercontrol()
{
	while(true)
	{
		arcade(vexRT[Ch1], vexRT[Ch2]);
		motor[Intake2] = vexRT[Ch3];
		motor[Intake] = vexRT[Ch4];
	}
}

void flagToPlatformSRT(int isBlue)
{
	goRobit(127, 127, ONE_TILE * 3);
	goRobit(127 * isBlue, -127 * isBlue, ONE_ROT);
	goRobit(127, 127, ONE_TILE * 2.5); //extra time to get onto the platform, FIXME
}
