#pragma config(Sensor, dgtl1,  bump,           sensorTouch)
#pragma config(Motor,  port1,           BLDrive,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           BRLift,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           BLLift,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           FRLift,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           FLLift,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           FRDrive,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           FLDrive,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          BRDrive,       tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Vex_Competition_Includes.c"

int drive = 0;

//basic stuff
void LDrive(int pwr)
{
	motor[FLDrive] = motor[BLDrive] = pwr;
}
void RDrive(int pwr)
{
	motor[FRDrive] = motor[BRDrive] = pwr;
}
void FourBar(int pwr)
{
	motor[BLLift] = motor[BRLift] = motor[FLLift] = motor[FRLift] = pwr;
}

//Drive Funcs
void arcade(int mov, int rot)
{
	LDrive(mov + rot);
	RDrive(mov - rot);
}
void tank(int left, int right)
{
	LDrive(left);
	RDrive(right);
}

void auton()
{

}

//Vex Funcs
void pre_auton()
{

}
task autonomous()
{
	//auton();
}
task usercontrol()
{
	while(true)
	{
		tank(vexRT[Ch3], vexRT[Ch2]);
		//lift code
		if(vexRT[Btn6U])
		{
			FourBar(127);
		}
		else if(vexRT[Btn6D])
		{
			FourBar(-127);
		}
		else
		{
			FourBar(0);
		}
	}
}
