#pragma config(Motor,  port1,           FLDrive,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           BLDrive,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           BRDrive,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          FRDrive,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Vex_Competition_Includes.c"

//basic stuff
void LDrive(int pwr)
{
	motor[FLDrive] = motor[BLDrive] = pwr;
}
void RDrive(int pwr)
{
	motor[FRDrive] = motor[BRDrive] = pwr;
}

//Drive Funcs
void arcade(int mov, int rot)
{
	LDrive(mov + rot);
	RDrive(mov - rot);
}

//Vex Funcs
void pre_auton()
{

}
task autonomous()
{
	//auton();
}
task usercontrol()
{
	while(true)
	{
		arcade(vexRT[Ch3], vexRT[Ch4]);
	}
}
